spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 97cc9943bc02b8a19c39
            clientSecret: dfb04b9d874f2d4b3aaf9efbdae86655b3680905
  data:
    cassandra:
      keyspace-name: main
      username: lxyXIPycIGphOCubdgWYpEHq
      password: Pgh-aMvR4PRTtr92GZU6DsJ5ueZrU6MuP7BkCCv3CtO--L77TDxGyQkJCKdak3iGqJaGRgNwLiT8UzNAUKZKA.xr-6ON9I9-kyNetHJ81vHT_aDZ4GtZcMIPrcEk3q_N
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true
    
    
server:
  port: 8081
  
      
datastax.astra:
  secure-connect-bundle: secure-connect-mybookmark-new.zip
  
  
astra.db:
    id: 38ebe0ee-35a8-41b9-82b0-daca8d8bbae1
    region: us-east1
    keyspace: main
    application.token: AstraCS:lxyXIPycIGphOCubdgWYpEHq:93cc22444bc844e142fa71b2d5fb168636692c6ecb1f08c3aa4d4a917a4b8489

        
        