spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 97cc9943bc02b8a19c39
            clientSecret: dfb04b9d874f2d4b3aaf9efbdae86655b3680905
  data:
    cassandra:
      keyspace-name: main
      username: EsJyGziEkSvTEUESQkYtZrsL
      password: E4IorbEprTxG6_pWnsQMZJNhE8DHQMaHAwWTT,NUQc,9Ev5-7AFOLnkSnrDMWIfuABrZY52fu4MycXLkNh8NhEq_dHv7gggd3ah,r.UGobB,NA+jZ,UtSdj-o0txHCa,
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true
    
    
server:
  port: 8081
  
      
datastax.astra:
  secure-connect-bundle: secure-connect.zip
  
  
astra.db:
    id: 6d190bd8-376e-4fc1-b576-942cd734b583-1
    region: us-east1
    keyspace: main
    application.token: AstraCS:EsJyGziEkSvTEUESQkYtZrsL:4acd4e91e36ce772fc12130067117aa24de49a95228fbc56572730e6752c9f2e

        
        